POST  http://localhost:9001/categories HTTP/1.1
content-type: application/json
[
  {
    "code": "001",
    "designation": "Fresh Produce"
  },
  {
    "code": "002",
    "designation": "Dairy and Eggs"
  },
  {
    "code": "003",
    "designation": "Grains and Pasta"
  },
  {
    "code": "004",
    "designation": "Snacks and Sweets"
  }
]
